dist: trusty
sudo: false
language: cpp

before_install:
  # Install deps
  - sudo apt-get -qq update
  - sudo apt-get install -y git cmake g++ flex bison libbz2-dev libopenimageio-dev libtiff5-dev libpng12-dev libgtk-3-dev libopenexr-dev libgl1-mesa-dev python3-dev python3-pip
  # Install Boost
  - wget https://sourceforge.net/projects/boost/files/boost/1.56.0/boost_1_56_0.tar.gz
  - tar zxf boost_1_56_0.tar.gz
  - cd boost_1_56_0
  - ./bootstrap.sh --with-python=/usr/bin/python3
  - ./b2 -j 8 install --prefix=`pwd`/../boost_1_56_0-bin >/dev/null
  - cd ..
  - export LD_LIBRARY_PATH=`pwd`/boost_1_56_0-bin/lib:$LD_LIBRARY_PATH
  # Install Embree
  - wget https://github.com/embree/embree/releases/download/v2.17.1/embree-2.17.1.x86_64.linux.tar.gz
  - tar zxf embree-2.17.1.x86_64.linux.tar.gz
  - export LD_LIBRARY_PATH=`pwd`/embree-2.17.1.x86_64.linux/lib
  # Install Pillow
  - sudo pip3 install pillow
  # Set OpenMP threads
  - export OMP_NUM_THREADS=4

script:
  - cmake -D BOOST_SEARCH_PATH=`pwd`/boost_1_56_0-bin -D EMBREE_SEARCH_PATH=`pwd`/embree-2.17.1.x86_64.linux -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.4m.so -DPYTHON_INCLUDE_DIR=/usr/include/python3.4m -DPYTHON_INCLUDE_DIR2=/usr/include/python3.4m .
  - make
#  - make tests
